[package]
name = "installer"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_System_Registry",
    "Win32_UI_TextServices",
    "Win32_System_Com",
    "Win32_Foundation",
] }
